### ISSUE TITLE
LikeParameterBinding does not function properly when same parameter used multiple times [DATAJPA-873]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1230]
**[Eric Sirianni](https://jira.spring.io/secure/ViewProfile.jspa?name=sirianni)** opened **[DATAJPA-873](https://jira.spring.io/browse/DATAJPA-873?redirect=false)** and commented

In the following example (native query):

```
SELECT name, position(:myParam IN name) as pos
FROM foo
WHERE name LIKE %:myParam%
```

The `LikeParameterBinding` does not properly translate the second usage of the `:myParam` parameter.  If I remove the first usage of the `:myParam` parameter, the query behaves as intended

---

1 votes, 2 watchers

**Comment by l7777777b** [comment]
Exactly the same issue as mine. Currently to overcome this i use a different named parameter for each usage.

**Comment by gregturn** [comment]
This was resolved by #2939.

Related: #2760.

**Comment by falcononrails** [comment]
Hello,

I am upgrading from Spring Boot 3.0.9 to 3.1.3 and I'm having the same issue on this query (which was working perfectly before):

```
@Query(value = """
         /* select and joins */
         where
                and (:encryptedEmail = '' or :encryptedEmail is null or c.encrypted_email = :encryptedEmail) \
                and (:name = '' or :name is null or cp.name like %:name%) \
                and (org.id in :ids or coalesce(:ids) is null)
        """, nativeQuery = true)
    List<View> findAll(String encryptedEmail, String name, List<Integer> ids);
```
```
Caused by: java.lang.IllegalArgumentException: Already found parameter binding with same index / parameter name but differing binding type; Already have: ParameterBinding [identifier: idList, origin: MethodInvocationArgument[identifier=idList]], found ParameterBinding [identifier: idList, origin: MethodInvocationArgument[identifier=idList]]; If you bind a parameter multiple times make sure they use the same binding
	at org.springframework.util.Assert.isTrue(Assert.java:122)

```

What's surprising is that I'm using `encryptedEmail` and `name` twice both clauses, but the error arises only for `ids`. Has this been fixed only for certain cases?

**Comment by leo-jeff-app** [comment]
Same here, with boot `3.1.2` -> `3.1.3`

```diff
-    id 'org.springframework.boot' version '3.1.2'
+    id 'org.springframework.boot' version '3.1.3'
```

Symptoms same as in prev comment https://github.com/spring-projects/spring-data-jpa/issues/1230#issuecomment-1693586595

**Comment by alirezaalallah** [comment]
Actually , I have same situation in my query when I have upgraded to new version, I'm getting exactly this the error you are discussing.
Where clause in query is like `:cities is null or entity.city in (:cities)` , also I used `coalesce` function but it didn't work

**Comment by falcononrails** [comment]
@alirezaalallah, this has been resolved in 3.1.4-SNAPSHOT. Check this issue [here](https://github.com/spring-projects/spring-data-jpa/issues/3126).

**Comment by alirezaalallah** [comment]
> @alirezaalallah, @alianman, @SamTV12345, @leo-jeff-app this has been resolved in `3.1.4-SNAPSHOT`. Check this issue [here](https://github.com/spring-projects/spring-data-jpa/issues/3126).

As this is `snapshot` seems like I have to wait util final is released. By the way thanks for the update

**Comment by SamTV12345** [comment]
> > @alirezaalallah, @alianman, @SamTV12345, @leo-jeff-app this has been resolved in `3.1.4-SNAPSHOT`. Check this issue [here](https://github.com/spring-projects/spring-data-jpa/issues/3126).
> 
> As this is `snapshot` seems like I have to wait util final is released. By the way thanks for the update

Yes. Same case. I can't rollout snapshots in production 😄 . But great that this is presumably fixed in 3.1.4

**Comment by HengCC** [comment]
I've also encountered this issue, just saw this issue, and I tried upgrading to 3.1.4-snapshot locally, but the problem still persists. it tips:
```
 Already found parameter binding with same index / parameter name but differing binding type; Already have: ParameterBinding [identifier: userIds, origin: MethodInvocationArgument[identifier=userIds]], found ParameterBinding [identifier: userIds, origin: MethodInvocationArgument[identifier=userIds]]; If you bind a parameter multiple times make sure they use the same binding
	at org.springframework.util.Assert.isTrue(Assert.java:122)
```
