### ISSUE TITLE
NPE in JpaQueryCreator when query result is projection-based interface

### ISSUE THREAD

**Issue by cigaly** [spring-projects/spring-data-jpa#2408]
Bug has been introduced in Spaing Data JPA 2.6.1 which causes NPE to be thrown in org.springframework.data.jpa.repository.query.JpaQueryCreator when  query result is projection-based interface or generic class with projection-based interface as type parameter.

Attached is simple diff file that changes org.springframework.data.jpa.repository.sample.UserRepository to demonstrate such behaviour.

While testing, if noticed that NPE is not thrown when line 181 in org.springframework.data.jpa.repository.query.JpaQueryCreator is changed from

`Class<?> typeToRead = returnedType.getTypeToRead();`

to

`Class<?> typeToRead = returnedType.getReturnedType();`

but I do not know is this can be proper fix or not.

[bug.diff.txt](https://github.com/spring-projects/spring-data-jpa/files/7875095/bug.diff.txt)

[Additional "feature" is that this bug is causing test to throw NPE's in infinte loop]

**Comment by lukaseckert** [comment]
Confirmed after updating spring-boot from 2.6.2 to 2.6.3 with Repository Code like
```
public interface MyProjection {
    String getField1();
    String getField2();
    // ... more simple string getters
}

public interface MyJpaRepository {
    Optional<MyProjection> findFirstByField1Equals(String field1);
}
```
Causing a NPE since  `typeToRead` is null in `query = typeToRead.isInterface()` in JpaQueryCreator.java:181

**Comment by everflux** [comment]
A possible workaround is to use an abstract class instead of an interface type.

**Comment by cigaly** [comment]
Method ReturnedType.getReturnedType() must not be used with interface. In Spring Data Commons exists test org.springframework.data.repository.query.ReturnedTypeUnitTests.detectsProjection which is explicitely requesting that getReturnedType is returning null on interfaces:

`void detectsProjection() throws Exception {

	ReturnedType type = getReturnedType("findAllProjection");

	assertThat(type.getTypeToRead()).isNull();
	assertThat(type.getInputProperties()).contains("lastname");
}
`

It seems that (proper?) solution of this problem will be to replace line (which will throw NPE whenever type to read is interface)

`query = typeToRead.isInterface()`

with line

`query = returnedType.needsCustomConstruction()`

**Comment by achimgrimm** [comment]
Hi,
I was able to work around this using the `@Value` annotation.

The example above would look like this:
```
public interface MyProjection {
    @org.springframework.beans.factory.annotation.Value("#{target.field1}")
    String getField1();
    @org.springframework.beans.factory.annotation.Value("#{target.field1}")
    String getField2();
    // ... more simple string getters
}
```

**Comment by jonilsonds9** [comment]
Hi guys, the exact same thing happened to me too.

Repositories with closed projections break with the same error:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isInterface()" because "typeToRead" is null
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:181) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:152) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:59) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:95) ~[spring-data-commons-2.6.1.jar:2.6.1]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:81) ~[spring-data-commons-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.<init>(PartTreeJpaQuery.java:217) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:92) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	... 61 common frames omitted
```
I'm trying to upgrade from spring-boot 2.6.2 to 2.6.3 with Java 17 but I can't because of this error.

The temporary solution in my case is the same as reported by @achimgrimm, 

Or annotating the repository method with `@Query` and passing a manual query with the correct alias:
```java
@Query("select t.id as id, t.name as name from Table t t.id = :id")
    List<ProjectionName> findAllByProjection_Id(@Param("id") Long id);
```
And the projection with the following structure:
```java
public interface ProjectionName {
    Long getId();
    Long getName();
}
```
But it's not as interesting as before.

**Comment by odrotbohm** [comment]
This should be fixed now in 2.6, 2.7 and 3.0 snapshots.

**Comment by akuma8** [comment]
> This should be fixed now in 2.6, 2.7 and 3.0 snapshots.

Hi,
Sorry to reopen this but I still have the issue in the `2021.2.0-M2` milestone. 
I migrated from Spring Boot 2.6.3 to 2.7.0-M1, Spring Data Jpa version is 2.7.0-M2 and the issue is still there.
Should I downgraded the Spring Data's BOM version until the released of Spring Boot 2.7.0?

**Comment by odrotbohm** [comment]
The fix was applied post 2.7 M2. It’s gonna be shipped with the upcoming M3.

**Comment by jase52476** [comment]
I'm getting this after upgrading spring-boot-starter-parent 2.7.8 -> 2.7.9, it's pulling spring-data-jpa 2.7.8 from 2.7.7 and my repository that was working previously now is having a NPE :

`Caused by: java.lang.NullPointerException: null
	at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607)
	at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49)
	at org.springframework.data.jpa.repository.query.StringQuery.deriveCountQuery(StringQuery.java:119)`
	
on line 594, this string is created and it defaults to null if there's no match:

`String variable = matcher.matches() ? matcher.group(VARIABLE_NAME_GROUP_INDEX) : null;`

But the null is not handled on line 607:

```
if (nativeQuery && (variable.contains(",") || "*".equals(variable))) {
				replacement = "1";	
```

Should I make a new issue? Sorry, I've never had to open a ticket with Spring.  I searched the open issues and there was one other but didn't seem to be the same issue.

If I switch back to spring-boot 2.7.8 and do a mvn clean install it starts up just fine with no modification of my repository.

**Comment by cigaly** [comment]
No, this is something completely diferent. I've met problem you are talking about in version 3.0.something. Most likely your (native) query which is causing NPE is not select, but something that is updating data. For some reason, Spring Data Jpa is trying to create count query for that (modifying) query (why?), but regular expression that is used can not match query string (no select). I can only guess that authors of that part of code never expected such situation (why should modifying query have count query?) and did not checked for null.

Check if somebody already reported that bug, if not create a new issue.

**Comment by jase52476** [comment]
> No, this is something completely diferent. I've met problem you are talking about in version 3.0.something. Most likely your (native) query which is causing NPE is not select, but something that is updating data. For some reason, Spring Data Jpa is trying to create count query for that (modifying) query (why?), but regular expression that is used can not match query string (no select). I can only guess that authors of that part of code never expected such situation (why should modifying query have count query?) and did not checked for null.

Thanks for your help. It's actually a select going into a projection-based interface. There is a join on another table and a group by, but I've verified all the fields I'm selecting, and matched them to the type, but it seems there's an unhandled null in the new code.
