### ISSUE TITLE
IgnoreCase uses Upper function in repository method names and cannot be configured.

### ISSUE THREAD

**Issue by ViktarRVR** [spring-projects/spring-data-jpa#2420]
We use Spring Data JPA + Querydsl JPA. If we perform queries with `ignoreCase` keyword in repository methods Spring data JPA use `UPPER` function on parameters in SQL(as described in [documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation), Table 3. Supported keywords inside method names), but Querydsl JPA uses `LOWER` function. We should use two types of indexes or don't use `ignoreCase` keyword in repository methods.

It would be great, if it was possible to configured to use `UPPER` function or `LOWER` function in Spring Data JPA.

**Comment by mp911de** [comment]
FTR: https://github.com/querydsl/querydsl/blob/99e3ca936f46471bc61d9af6e1a3dbb16f3f12b3/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLTemplates.java

**Comment by steveratay** [comment]
I ran into the same problem in the query by example code.  It also appears to be hard-coded to use a lower conversion.  As stated above, this is challenging because I only want to maintain a single case-insensitive index on either the upper or lowercase version of certain columns.

See https://github.com/spring-projects/spring-data-jpa/blob/main/src/main/java/org/springframework/data/jpa/convert/QueryByExamplePredicateBuilder.java#L182.

It would be great if this were able to be customized in the ExampleMatcher methods.

**Comment by gregturn** [comment]
Whereas another knob would work, I wonder if it isn't simpler to just update things to use `UPPER` across the board.

**Comment by schauder** [comment]
Going consistently with `lower` sounds like a good way to go. Please make sure to have this change included in release notes since it might disable existing indexes and therefore cause a performance degradation when not addressed.

**Comment by gregturn** [comment]
This has been merged to `main` and to `3.0.x`.

**Comment by gregturn** [comment]
Release notes https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-2021.2-(Raj)-Release-Notes-(Preview) have been updated.

**Comment by OrangeDog** [comment]
Did this get reverted, or did I miss something? According to the logged HQL, 3.2.2 is using `upper` instead of `lower`.

**Comment by danwatt** [comment]
I am with @OrangeDog  - I just wrapped up dropping an UPPER index thinking this had been resolved in 2.7.x, only to discover that a QueryDsl `IgnoreCase` method is still generating `where upper(...)=upper(?)`

I am on `2.7.18` for this project, upgraded to 2.6.x.

**Comment by OrangeDog** [comment]
@danwatt QueryDSL is using `lower`, repositories are using `upper`. Same as described in the original issue.

**Comment by OrangeDog** [comment]
@gregturn @mp911de can this be reopened? It was not fixed. It looks like someone messed up resolving conflicts in the merge or something.

**Comment by mp911de** [comment]
Sure. We've started exploring configuration for ignore-case transformations with https://github.com/spring-projects/spring-data-jpa/pull/3653/files#diff-fdc19ed3d18aab513d05cd0418ab02dbaa8f1bdf5f8f8574d26d1ecdd9914486

**Comment by OrangeDog** [comment]
Is there any plan to actually fix this issue as originally intended (i.e. make everything use `lower`)? That would be much easier than adding new configuration.
