### ISSUE TITLE
Passing null as stored procedure argument is broken in v2.7.0 (works in v2.6.8).

### ISSUE THREAD

**Issue by denis111** [spring-projects/spring-data-jpa#2544]
With spring.jpa.properties.hibernate.proc.param_null_passing=true we can pass null as stored procedure as parameter without any problem with Spring Boot 2.6.8 but upgrading to v2.7.0 throws exception with the same Hibernate version. I've tried only with PostgreSQL and UUID as procedure parameter but I suppose it could be for any type of DB and parameters. The exception is:
`Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Bind value [org.hibernate.jpa.TypedParameterValue@5b1420f9] was not of specified type [class java.util.UUID; nested exception is java.lang.IllegalArgumentException: Bind value [org.hibernate.jpa.TypedParameterValue@5b1420f9] was not of specified type [class java.util.UUID`

Example:
```java
public interface TestModelRepository extends JpaRepository<TestModel, Long> {
  @Procedure("countByUuid")
  void countUuid(UUID one);
}
```
then just call `testModelRepository.countUuid(null)`.
I've prepared a sample project to reproduce the problem, just change Spring Boot version to 2.6.8 and it works fine: https://github.com/denis111/spring-data-jpa270test

**Comment by SchlauFuchs** [comment]
This might explain our current issue using an @Procedure annotation with a number of parameters where one is nullable, and we suddenly get a Bind value issue. Using V2.7.2

**Comment by stylepatrick** [comment]
The same problem occurs with Oracle database. Calling a procedure with a nullable parameter leads to the following error:

`java.lang.IllegalArgumentException: Bind value [org.hibernate.jpa.TypedParameterValue@42dae24d] was not of specified type [class java.lang.String`

Is a correction planned or are nullable parameters no longer supported?

**Comment by SchlauFuchs** [comment]
is this still broken with 2.7.3? we downgraded to 2.6.8, waiting for the fix.

**Comment by quaff** [comment]
> is this still broken with 2.7.3? we downgraded to 2.6.8, waiting for the fix.

It should fixed in 2.7.3, but it's not released yet. @gregturn

**Comment by denis111** [comment]
I've just tried 2.7.4 and the issue is still there, I have updated my test project.

**Comment by denis111** [comment]
v2.7.5, the issue is still there, updated my test project.

**Comment by quaff** [comment]
@denis111 It should be fixed at hibernate side, I have created https://github.com/hibernate/hibernate-orm/pull/5438

**Comment by kashann** [comment]
Any idea when will the issue be fixed?

**Comment by denis111** [comment]
The issue is still present un v2.7.6 but it's solved in v3.0.0. I've updated my test project and created the branch `spring-boot-3`.

**Comment by gregturn** [comment]
The issue was clearly mended when Spring Data JPA moved to Hibernate 6 in Spring Boot `3.0.0-M4` (Spring Data `2022.0.0-M5`).

You can see [ALL the changes that happened in Spring Data JPA](https://github.com/spring-projects/spring-data-jpa/compare/3.0.0-M4...3.0.0-M5) between `3.0.0-M4` and `3.0.0-M5`, and nothing stands out except upgrading to Hibernate 6 and properly handling nulls for LIKEs. The former will never be backported to `2.7.x` and the latter already has been in `2.7.6`.

**Comment by SchlauFuchs** [comment]
Thank you for that analysis, but can you do one for what happened between
2.6.8 and 2.7.0? It was working and then not anymore.

**Comment by gregturn** [comment]
I have created a test case inside Spring Data JPA `2.7.x` that replicates the error message first reported at the top. I want to isolate if this is specific to `UUID` or is something else.

**Comment by gregturn** [comment]
Okay, changing the reproducer's type to `uuid` to `varchar`/`String` results in a slightly different error. But it has the same pattern.

**Comment by gregturn** [comment]
Looks like our `TypedParameterValue` solution to support Hibernate is the culprit here. If I look for that type when setting stored procedure parameters, and dereference it, it works. I believe that was introduced in 2.7, which would explain why it still works in 2.6.

**Comment by gregturn** [comment]
Thanks @quaff for submitting the PR (https://github.com/spring-projects/spring-data-jpa/issues/2544#issuecomment-1286689469). Until they accept that PR, I'm can conditionally de-reference the `TypedParameterValue` on our end for stored procedure calls.

**Comment by gregturn** [comment]
Issue resolved. Check it out in `2.7.7-SNAPSHOT`.

**Comment by gregturn** [comment]
Merged forward to `3.0.x` and `main`.

While `TypedParameterValue` is handled properly in Hibernate 6.1 for general parameter types, it still requires dereferencing for temporal types.

CC @quaff

**Comment by denis111** [comment]
@gregturn it looks like it didn't get to Spring Boot 2.7.7 (I've updated my test project), should we wait for 2.7.8 or it will never be included in 2.7.x branch?

**Comment by SchlauFuchs** [comment]
@gregturn We still have this issue. Here a stack trace:

```
org.springframework.dao.InvalidDataAccessApiUsageException: Bind value [org.hibernate.jpa.TypedParameterValue@2cff35e7] was not of specified type [class java.lang.String; nested exception is java.lang.IllegalArgumentException: Bind value [org.hibernate.jpa.TypedParameterValue@2cff35e7] was not of specified type [class java.lang.String
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy3/jdk.proxy3.$Proxy279.assignJob(Unknown Source)
```

**Comment by SchlauFuchs** [comment]
Seems like there is a dependency mismatch. Using springboot-starter-data-jpa 2.7.8 it works, and it has the transient dependency to spring-data-jpa 2.7.7.
