### ISSUE TITLE
Unable to do a query with a null paramater with 'contains' and 'is null' in 2.7.0

### ISSUE THREAD

**Issue by pkernevez** [spring-projects/spring-data-jpa#2570]
We works with postgresql event I don't think it change something.
This was working fine until 2.6.4 (included).

We had a query with a param that should be null.
```java
    @Query("SELECT b FROM BenchmarkEntity b WHERE (:name is null or b.name like %:name%) "
           "and (:reference is null or b.reference = :reference) ")
    List<BenchmarkEntity> findBenchmarks(String name, Boolean reference);
```
It avoids us to use a 'like' when the optional parameter 'name' is null.

Before 2.6.4, it returned all the tables rows.
With 2.7.0, it doesn't return any row => no match

The behaviour changed for the parameter pass to the sql query.
Before : 2.6.4 (working)
```
11:37:57.415 TRACE [,,] 33012 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [1] as [VARCHAR] - [null]
11:37:57.415 TRACE [,,] 33012 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [2] as [VARCHAR] - [null]
11:37:57.416 TRACE [,,] 33012 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [3] as [BOOLEAN] - [null]
11:37:57.416 TRACE [,,] 33012 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [4] as [BOOLEAN] - [null]
```

With 2.7.0 (broken):
```java
11:48:41.547 TRACE [,,] 34086 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [1] as [VARCHAR] - [%org.hibernate.jpa.TypedParameterValue@78184e8c%]
11:48:41.547 TRACE [,,] 34086 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [2] as [VARCHAR] - [%org.hibernate.jpa.TypedParameterValue@78184e8c%]
11:48:41.548 TRACE [,,] 34086 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [3] as [BOOLEAN] - [null]
11:48:41.548 TRACE [,,] 34086 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [4] as [BOOLEAN] - [null]
```
It seems that the bind value is the encapsulating instance (TypedParameterValue) instead of it's internal value, but only for String value (works with other types).

What is strange is that the QueryParameters object has a list of TypedValue (normal), and for the boolean, the value is 'null'
<img width="401" alt="image" src="https://user-images.githubusercontent.com/338699/174047672-17cd375d-af4a-46bb-b1fa-175fac6ea1c4.png">

But for the String the value is not null but '%org.hibernate.jpa.TypedParameterValue@7eaf7a70%'
<img width="710" alt="image" src="https://user-images.githubusercontent.com/338699/174047974-2efe30a9-2ab6-43f9-af97-c01233be9f46.png">

When I remove the 'contains' part in the query, the behaviour didn't change between the 2.6.4 and the 2.7.0, meaning it works fine with 2.7.0.
```java
    @Query("SELECT b FROM BenchmarkEntity b WHERE (:name is null) "
           "and (:reference is null or b.reference = :reference) ")
    List<BenchmarkEntity> findBenchmarks(String name, Boolean reference);
```

```
11:37:57.415 TRACE [,,] 33012 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [1] as [VARCHAR] - [null]
11:37:57.416 TRACE [,,] 33012 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [2] as [BOOLEAN] - [null]
11:37:57.416 TRACE [,,] 33012 --- [           main] o.h.t.d.sql.BasicBinder        : binding parameter [3] as [BOOLEAN] - [null]
```

That seems it's the fact that the param is use in a 'contains' clause change its value instead of the binding.

This issue may linked to https://github.com/spring-projects/spring-data-jpa/issues/2544 and https://github.com/spring-projects/spring-data-jpa/issues/2549

**Comment by jochenwierum** [comment]
Possibly a duplicate of https://github.com/spring-projects/spring-data-jpa/issues/2548?

**Comment by pkernevez** [comment]
Yes, duplicate of https://github.com/spring-projects/spring-data-jpa/issues/2548

**Comment by gregturn** [comment]
Resolved by the linked commit.

**Comment by clojj** [comment]
@gregturn 
Hi! so the fix for this issue is not available in Spring Releases 2.7.x ..right ?

**Comment by dvag-joerg-winter** [comment]
@gregturn 
Hi, so the fix for this issue is not available in Spring Releases 2.7.x ..right ?

**Comment by joheb-mohemian** [comment]
@dvag-joerg-winter Would like a fix too...we currently use 2.7.x but override the spring-data-bom.version property as 
` <spring-data-bom.version>2021.1.3</spring-data-bom.version>`, i.e. a version that did not have the bug...

**Comment by gregturn** [comment]
Backported to `2.7.x` with f0216b0d9c2f942ade7d90e79a0fa6b669f5ae6b

**Comment by dvag-joerg-winter** [comment]
@gregturn 
Is this already fixed in https://github.com/spring-projects/spring-boot/issues/32275
or later ?

**Comment by Axinet** [comment]
Looks like the issue is still present with newest spring-boot `2.7.5` version :(. Just encountered it when trying to upgrade from `2.6.x` line and found this issue.

**Comment by edudar** [comment]
It does not seem to work with nullable temporal parameters either. `QueryParameterSetter` casts `value` to `Date` explicitly. The actual type is `TypedParameterValue` since 2.7, though. This cause a standard class case exception like 
```
java.lang.ClassCastException: class org.hibernate.jpa.TypedParameterValue cannot be cast to class java.util.Date
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$NamedOrIndexedQueryParameterSetter.lambda$setParameter$1(QueryParameterSetter.java:98)
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$ErrorHandling$1.execute(QueryParameterSetter.java:140)
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$NamedOrIndexedQueryParameterSetter.setParameter(QueryParameterSetter.java:98)
```

Should this be a new issue, or is it linked to some already mentioned one?

**Comment by gregturn** [comment]
Bump your app's `spring-data-bom.version` up to `2021.2.7-SNAPSHOT` and you should see the patch.

**Comment by gregturn** [comment]
Check out `2.7.6`. For Spring Boot 2.7, you can get this if you bump `spring-data-bom.version` up to `2021.2.6` or higher. 

FYI: we've had several related tickets get reported as this solving their issue.

**Comment by joheb-mohemian** [comment]
@gregturn This works indeed. But forgive me for asking, if spring-boot 2.7.x is compatible with `spring-data-bom.version >= 2021.2.6`, why isn't there a spring-boot 2.7.x release that includes one of these spring-data versions? Wouldn't the fix for this bug justify a minor release?
